version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: customerManagerService
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27017:27017"
  app:
    image: app
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
       APP_DB_HOST: mongodb
       APP_DB_NAME: testdb
       APP_DB_USER: customerManagerService
       APP_DB_PASS: 1234
       APP_MQ_HOST: rabbitmq
       APP_MQ_USER: guest
       APP_MQ_PASSWORD: guest
    volumes:
      - /data/springboot-docker-compose-app
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - mongodb